export const ROUTE_SELECTED = 'ROUTE_SELECTED';
export const ROUTE_DESELECTED = 'ROUTE_DESELECTED';
export const SET_DIRECTIONS = 'SET_DIRECTIONS';
export const SET_WALKING_TIME = 'SET_WALKING_TIME'
export const SET_EXPANDED_CIRCLE = 'SET_EXPANDED_CIRCLE'
export const SET_EXPANDED_WALKING_TIME = 'SET_EXPANDED_WALKING_TIME';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_MARKERS = 'SET_MARKERS';
export const SET_EXPANDED_MARKERS = 'SET_EXPANDED_MARKERS';
export const SET_SURGE = 'SET_SURGE';
export const DISABLE_SURGE = 'DISABLE_SURGE';

export const REQUEST_ROUTES = 'REQUEST_ROUTES';
export const REQUEST_EXPANDED_ROUTES = 'REQUEST_EXPANDED_ROUTES';

export const RECEIVE_ROUTES_UBER = 'RECEIVE_ROUTES_UBER';
export const RECEIVE_ROUTES_LYFT = 'RECEIVE_ROUTES_LYFT';

export const RECEIVE_EXPANDED_ROUTES = 'RECEIVE_EXPANDED_ROUTES';
export const NO_EXPANDED_ROUTES = 'NO_EXPANDED_ROUTES';

export const INVALID_ROUTES = 'INVALID_ROUTES';
