// Active route selection and lightbox triggers
export const ROUTE_SELECTED = 'ROUTE_SELECTED';
export const ROUTE_DESELECTED = 'ROUTE_DESELECTED';
export const SET_MARKERS = 'SET_MARKERS';
export const SET_EXPANDED_MARKERS = 'SET_EXPANDED_MARKERS';

// API call flags
export const REQUEST_ROUTES = 'REQUEST_ROUTES';

export const RECEIVE_ROUTES_UBER = 'RECEIVE_ROUTES_UBER';
export const RECEIVE_ROUTES_LYFT = 'RECEIVE_ROUTES_LYFT';

export const RECEIVE_EXPANDED_ROUTES = 'RECEIVE_EXPANDED_ROUTES';
export const NO_EXPANDED_ROUTES = 'NO_EXPANDED_ROUTES';

export const INVALID_ROUTES = 'INVALID_ROUTES';

export const CURRENT_ADDRESS = 'CURRENT_ADDRESS';
